import m from "mithril";
import "~/styles.css";

import Header from "~/components/header";
import Container from "~/components/container";
import Plate from "~/components/plate";
import Link from "~/components/link";

const Main: m.Component = {
  view: (v) => {
    return [m(Header), 
      m(Container,
        m(".", {style: {
          display: "grid",
          gridTemplateColumns: "1fr 1fr",
          gridTemplateRows: "1fr 1fr 1fr 1fr",
          gap: "0rem",
          fontSize: "1.5rem",
          width: "content-min",
          margin: "2rem",
        }},
          m("h1", {style:{gridColumn: "2", gridRow: "1"}}, m("span", {style: {color: "rgb(0, 255, 0)"}}, "sh"), "are"),
          m("h1", {style:{gridColumn: "1", gridRow: "2", justifySelf: "end"}}, "yo"),
          m("h1", {style:{gridColumn: "2", gridRow: "2", color: "rgb(0, 255, 0)"}}, "ur"),
          m("h1", {style:{gridColumn: "2", gridRow: "3"}}, m("span", {style: {color: "rgb(0, 255, 0)"}}, "mu"), "sic"),
          m("h1", {style:{gridColumn: "2", gridRow: "4", color: "rgb(0, 255, 0)"}}, ".com"),
        )
      ),
      m(Container,
        m(Plate,
          m("h1", "Welcome to shurmu"),
          m("p", "This is the home page."),
        ),
        m(Plate,
          m("h1", "Dinosaur Jr."),
          m("p", "This is the artist page."),
        ),
        m(Plate,
          m("h1", "Upload"),
          m("p", "This is the upload page."),
        ),
      ),
      m(Container,
        m(Plate,
          m("h1", "Welcome to shurmu"),
          m("p", "This is the home page."),
        ),
        m(Plate,
          m("h1", "Dinosaur Jr."),
          m("p", "This is the artist page."),
        ),
        m(Plate,
          m("h1", "Upload"),
          m("p", "This is the upload page."),
        ),
      ),
      m(Container,
        m(Plate,
          m("h1", "Welcome to shurmu"),
          m("p", "This is the home page."),
        ),
        m(Plate,
          m("h1", "Dinosaur Jr."),
          m("p", "This is the artist page."),
        ),
        m(Plate,
          m("h1", "Upload"),
          m("p", "This is the upload page."),
        ),
      ),
      m(Container,
        m(Plate,
          m("h1", "Welcome to shurmu"),
          m("p", "This is the home page."),
        ),
        m(Plate,
          m("h1", "Dinosaur Jr."),
          m("p", "This is the artist page."),
        ),
        m(Plate,
          m("h1", "Upload"),
          m("p", "This is the upload page."),
        ),
      ),
      m(Container,
        m(Plate,
          m("h1", "Welcome to shurmu"),
          m("p", "This is the home page."),
        ),
        m(Plate,
          m("h1", "Dinosaur Jr."),
          m("p", "This is the artist page."),
        ),
        m(Plate,
          m("h1", "Upload"),
          m("p", "This is the upload page."),
        ),
      ),
      m(Container,
        m(Plate,
          m("h1", "Welcome to shurmu"),
          m("p", "This is the home page."),
        ),
        m(Plate,
          m("h1", "Dinosaur Jr."),
          m("p", "This is the artist page."),
        ),
        m(Plate,
          m("h1", "Upload"),
          m("p", "This is the upload page."),
        ),
      ),
      m(Container,
        m(Plate,
          m("h1", "Welcome to shurmu"),
          m("p", "This is the home page."),
        ),
        m(Plate,
          m("h1", "Dinosaur Jr."),
          m("p", "This is the artist page."),
        ),
        m(Plate,
          m("h1", "Upload"),
          m("p", "This is the upload page."),
        ),
      ),
      m(Container,
        m(Plate,
          m("h1", "Welcome to shurmu"),
          m("p", "This is the home page."),
        ),
        m(Plate,
          m("h1", "Dinosaur Jr."),
          m("p", "This is the artist page."),
        ),
        m(Plate,
          m("h1", "Upload"),
          m("p", "This is the upload page."),
        ),
      ),
    ];
  },
};

export default Main;
